// <auto-generated>
// Rewired Constants
// This list was generated on 26/02/2019 6:56:20 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace TMechs.Controls {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Vertical")]
        public const int MOVE_VERTICAL = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Horizontal")]
        public const int MOVE_HORIZONTAL = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Camera Vertical")]
        public const int CAMERA_VERTICAL = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Camera Horizontal")]
        public const int CAMERA_HORIZONTAL = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Jump")]
        public const int JUMP = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Zoom")]
        public const int ZOOM = 5;
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int SYSTEM = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Main Player")]
        public const int MAIN_PLAYER = 0;
    }
}
