// <auto-generated>
// Rewired Constants
// This list was generated on 7/06/2019 7:13:58 AM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace TMechs.Controls {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Vertical")]
        public const int MOVE_VERTICAL = 0;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Move Horizontal")]
        public const int MOVE_HORIZONTAL = 1;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Camera Vertical")]
        public const int CAMERA_VERTICAL = 2;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Camera Horizontal")]
        public const int CAMERA_HORIZONTAL = 3;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Jump")]
        public const int JUMP = 4;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Lock On")]
        public const int LOCK_ON = 5;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Dash")]
        public const int DASH = 6;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Interact")]
        public const int INTERACT = 7;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Attack")]
        public const int ATTACK = 8;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Camera Center")]
        public const int CAMERA_CENTER = 9;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Menu")]
        public const int MENU = 10;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Left Arm")]
        public const int LEFT_ARM = 16;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Right Arm")]
        public const int RIGHT_ARM = 17;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Sprint")]
        public const int SPRINT = 18;
        // UI
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIVertical")]
        public const int UIHORIZONTAL = 11;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIVertical")]
        public const int UIVERTICAL = 12;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UISubmit")]
        public const int UISUBMIT = 13;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UICancel")]
        public const int UICANCEL = 14;
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "UI", friendlyName = "UIAlternate")]
        public const int UIALTERNATE = 15;
    }
    public static partial class Category {
        public const int DEFAULT = 0;
        public const int UI = 1;
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int SYSTEM = 9999999;
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "Main Player")]
        public const int MAIN_PLAYER = 0;
    }
}
